services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/data:/data/db

  node-app:
    build: .
    container_name: crud-api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/crud_api
      - PORT=3000
    depends_on:
      - mongo
    restart: always
